# Generated by Django 3.2.3 on 2023-12-11 00:44

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231210_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=50)], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2), django.core.validators.MaxLengthValidator(limit_value=50)], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(limit_value=5), django.core.validators.MaxLengthValidator(limit_value=50)], verbose_name='username'),
        ),
    ]
